name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubunto-latest
    container:
      image: python:3.11-slim
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Intall dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -q